// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ytdlp} from '../models';

export function SetupResources():Promise<void>;

export function StartDownload(arg1:string,arg2:ytdlp.SplitState):Promise<void>;
