// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetupResources() {
  return window['go']['main']['App']['SetupResources']();
}

export function StartDownload(arg1, arg2) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2);
}
