name: Wails build

on:
  push:
    tags:
      # Match any new tag
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'ytdlp.exe'
            platform:  'windows/amd64'
            os: 'windows-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set Versions
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')
            const dash_index = no_v.lastIndexOf('-')
            const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
            core.setOutput('tag', tag)
            core.setOutput('no-v', no_v)
            core.setOutput('no-dash', no_dash)
      - name: Replace env in main.go (appVersion, apiUrl, apiKey)
        run: |
          (Get-Content main.go) | ForEach-Object { $_ -replace 'appVersion := ".*"', 'appVersion := "${{ steps.set_version.outputs.no-dash }}"' } | Set-Content main.go
      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.22.3'
        env:
          VITE_APP_VERSION: ${{ steps.set_version.outputs.no-dash }}